version: '3.1'

services:
  db:
    image: postgres:12
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: qwepoi123
    ports:
      - "5432:5432"
    volumes:
      - meu_volume_pgdata:/var/lib/postgresql/data
    command: 
      bash -c "psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'prototipo'\" | grep -q 1 || psql -U postgres -c \"CREATE DATABASE prototipo\" && postgres"

volumes:
  meu_volume_pgdata:

